version: "3.9"

services:

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Tochka
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: Tochka
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: fastapi_app
    command: ./start.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql+asyncpg://Tochka:123123@db:5432/Tochka
      - REDIS_URL=redis://redis:6379/0

  alembic:
    build: .
    container_name: alembic_runner
    command: ./wait_alembic.sh db alembic upgrade head
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://Tochka:123123@db:5432/Tochka

  worker:
    build: .
    container_name: celery_worker
    command: celery -A celery_app worker --loglevel=info -Q matching
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://Tochka:123123@db:5432/Tochka
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
