version: "3.9"

services:

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - /srv/postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache

  web:
    build: .
    container_name: fastapi_app
    command: ./start.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

  alembic:
    build: .
    container_name: alembic_runner
    command: ./wait_alembic.sh db alembic upgrade head
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

  worker:
    build: .
    container_name: celery_worker
    command: celery -A celery_app worker --loglevel=info -Q matching 
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  postgres_data:
