from alembic import op
import sqlalchemy as sa


revision = '104b4312d2bc'
down_revision = 'b208c4d76f7b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balances', 'frozen',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('balances_user_id_fkey'), 'balances', type_='foreignkey')
    op.create_foreign_key(None, 'balances', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('transactions_sell_order_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_buy_order_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'orders', ['buy_order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'orders', ['sell_order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_buy_order_id_fkey'), 'transactions', 'orders', ['buy_order_id'], ['id'])
    op.create_foreign_key(op.f('transactions_sell_order_id_fkey'), 'transactions', 'orders', ['sell_order_id'], ['id'])
    op.create_index(op.f('ix_transactions_ticker'), 'transactions', ['ticker'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_orders_user_id_status'), 'orders', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_orders_ticker_status'), 'orders', ['ticker', 'status'], unique=False)
    op.create_index(op.f('ix_orders_ticker'), 'orders', ['ticker'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.drop_constraint(None, 'balances', type_='foreignkey')
    op.create_foreign_key(op.f('balances_user_id_fkey'), 'balances', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_balances_user_id_ticker'), 'balances', ['user_id', 'ticker'], unique=False)
    op.alter_column('balances', 'frozen',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###