from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '5210cff8b329'
down_revision = '3ead17749da6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'direction',
               existing_type=postgresql.ENUM('BUY', 'SELL', name='order_directions'),
               type_=sa.Enum('BUY', 'SELL', name='order_directions', native_enum=False),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('NEW', 'EXECUTED', 'PARTIALLY_EXECUTED', 'CANCELLED', name='order_statuses'),
               type_=sa.Enum('NEW', 'EXECUTED', 'PARTIALLY_EXECUTED', 'CANCELLED', name='order_statuses', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('NEW', 'EXECUTED', 'PARTIALLY_EXECUTED', 'CANCELLED', name='order_statuses', native_enum=False),
               type_=postgresql.ENUM('NEW', 'EXECUTED', 'PARTIALLY_EXECUTED', 'CANCELLED', name='order_statuses'),
               existing_nullable=True)
    op.alter_column('orders', 'direction',
               existing_type=sa.Enum('BUY', 'SELL', name='order_directions', native_enum=False),
               type_=postgresql.ENUM('BUY', 'SELL', name='order_directions'),
               existing_nullable=False)
    # ### end Alembic commands ###